///  Demonstrates how to limit the pseudo-random numbers generated by 
//  Random class.
//********************************************************************


import java.util.Scanner;
import java.util.Random;




public class RandomExample {

	public static void main(String[] args) 
	{
	
		int limit, autoNumber;
		
		Random myRandom = new Random();
		Scanner keyboard = new Scanner (System.in);
		
		System.out.print("Enter the range for a randomly generated  number:");
		
		limit = keyboard.nextInt();
		
		autoNumber = myRandom.nextInt(limit);
		
		          
       		System.out.print("Random number is: " + autoNumber);
		
				
	}

}
